version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "daily"
    target_branch: "master"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    version_requirement_updates: "increase_versions"
